### ISSUE TITLE
Falta el enlace en la sección `about` de este repo al enlace de despliegue

### ISSUE THREAD

**Issue by crguezl** [ULL-MFP-AET-2122/static-generator-alejandro-gonzalez-gonzalez-alu0100879902#1]
@ alu0100879902

Falta el enlace en la sección **about** de este repo al enlace de despliegue

**Comment by alu0100879902** [comment]
Enlace añadido.

https://github.com/ULL-MFP-AET-2122/static-generator-alejandro-gonzalez-gonzalez-alu0100879902

**Comment by crguezl** [comment]
👍
